"""Phase 10.2 Add User model and user relationships

Revision ID: dc0e52173676
Revises: befa9e13a93f
Create Date: 2026-10-03 12:35:34.770478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0e52173676'
down_revision: Union[str, None] = 'befa9e13a93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
